### ISSUE TITLE
Feature Request: Update Simple Calculator with Scientific Calculations, Invoice Button, and Theme Change

### ISSUE THREAD

**Issue by narendrachaurasia** [Anikesh02/Basic-Calculator#1]
would like to propose several updates to the existing Simple Calculator project to enhance its functionality and user experience.

Proposed Changes
Add Scientific Calculations:
Implement additional functions for scientific calculations (e.g., trigonometric functions, logarithms, exponents).
Ensure that the UI accommodates these new features.
Add Invoice-Making Button:
Introduce a button that allows users to create an invoice based on the calculations made.
The feature should include options to enter item details and amounts, and generate a simple invoice format.
Theme Change:
Implement a theme toggle feature that allows users to switch between light and dark modes.
Ensure the UI adapts correctly to the selected theme for better accessibility.
Benefits
These enhancements will not only improve the calculator's functionality but also make it more user-friendly and appealing to a wider audience.

**Comment by Anikesh02** [comment]
@narendrachaurasia assigned

**Comment by davyrap** [comment]
i can add theme switching functionality and do some general improvement to the UI. Is this supposed to be like a phone-only app?
